### ISSUE TITLE
Not compatible with android gradle plugin v1.1.0-rc1

### ISSUE THREAD

**Issue by evant** [evant/holdr#46]
```
No such property: defaultConfigData for class: com.android.build.gradle.LibraryPlugin
	at me.tatarka.holdr.gradle.HoldrPlugin.getManifestPackage(HoldrPlugin.groovy:74)
	at me.tatarka.holdr.gradle.HoldrExtension.getHoldrPackage(HoldrExtension.groovy:25)
	at me.tatarka.holdr.gradle.HoldrExtension_Decorated.getHoldrPackage(Unknown Source)
	at org.gradle.api.internal.BeanDynamicObject$MetaClassAdapter.getProperty(BeanDynamicObject.java:153)
	at org.gradle.api.internal.BeanDynamicObject.getProperty(BeanDynamicObject.java:107)
	at org.gradle.api.internal.CompositeDynamicObject.getProperty(CompositeDynamicObject.java:78)
	at me.tatarka.holdr.gradle.HoldrExtension_Decorated.getProperty(Unknown Source)
	at me.tatarka.holdr.gradle.HoldrPlugin$_applyHoldrPlugin_closure4_closure5.doCall(HoldrPlugin.groovy:55)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:63)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:130)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:110)
	at org.gradle.api.internal.AbstractTask.configure(AbstractTask.java:482)
	at org.gradle.api.internal.project.AbstractProject.task(AbstractProject.java:879)
	at me.tatarka.holdr.gradle.HoldrPlugin$_applyHoldrPlugin_closure4.doCall(HoldrPlugin.groovy:54)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:63)
	at org.gradle.listener.ActionBroadcast.execute(ActionBroadcast.java:39)
	at org.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:165)
	at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:160)
	at com.android.build.gradle.LibraryExtension.addVariant(LibraryExtension.groovy:68)
	at com.android.build.gradle.internal.VariantManager.createApiObjects(VariantManager.java:625)
	at com.android.build.gradle.internal.VariantManager.createAndroidTasks(VariantManager.java:246)
	at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.groovy:431)
	at com.android.build.gradle.BasePlugin$_createTasks_closure9.doCall(BasePlugin.groovy:373)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
	at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:83)
	at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:31)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy13.afterEvaluate(Unknown Source)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:79)
```

**Comment by evant** [comment]
Fixed in 1.4.1
